/********************************************************************
* Main_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Main_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMain_dict();
extern void G__cpp_setup_inheritanceMain_dict();
extern void G__cpp_setup_typetableMain_dict();
extern void G__cpp_setup_memvarMain_dict();
extern void G__cpp_setup_globalMain_dict();
extern void G__cpp_setup_memfuncMain_dict();
extern void G__cpp_setup_funcMain_dict();
extern void G__set_cpp_environmentMain_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "tree_structure.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Main_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__Main_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Main_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Main_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Main_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Main_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Main_dictLN_SiHit;
extern G__linked_taginfo G__Main_dictLN_SiHitcLcLSortByDetector;
extern G__linked_taginfo G__Main_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__Main_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Main_dictLN_SiHitcLcLSortByHit;
extern G__linked_taginfo G__Main_dictLN_vectorlESiHitcLcLSortByDetectorcOallocatorlESiHitcLcLSortByDetectorgRsPgR;
extern G__linked_taginfo G__Main_dictLN_reverse_iteratorlEvectorlESiHitcLcLSortByDetectorcOallocatorlESiHitcLcLSortByDetectorgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Main_dictLN_vectorlESiHitcLcLSortByHitcOallocatorlESiHitcLcLSortByHitgRsPgR;
extern G__linked_taginfo G__Main_dictLN_reverse_iteratorlEvectorlESiHitcLcLSortByHitcOallocatorlESiHitcLcLSortByHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Main_dictLN_PCHit;
extern G__linked_taginfo G__Main_dictLN_PCHitcLcLSortByPC;
extern G__linked_taginfo G__Main_dictLN_vectorlEPCHitcLcLSortByPCcOallocatorlEPCHitcLcLSortByPCgRsPgR;
extern G__linked_taginfo G__Main_dictLN_reverse_iteratorlEvectorlEPCHitcLcLSortByPCcOallocatorlEPCHitcLcLSortByPCgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Main_dictLN_Track;
extern G__linked_taginfo G__Main_dictLN_TrackcLcLTrackEvent;
extern G__linked_taginfo G__Main_dictLN_vectorlETrackcLcLTrackEventcOallocatorlETrackcLcLTrackEventgRsPgR;
extern G__linked_taginfo G__Main_dictLN_reverse_iteratorlEvectorlETrackcLcLTrackEventcOallocatorlETrackcLcLTrackEventgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
