/********************************************************************
* organize_dictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error organize_dictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableorganize_dictionary();
extern void G__cpp_setup_inheritanceorganize_dictionary();
extern void G__cpp_setup_typetableorganize_dictionary();
extern void G__cpp_setup_memvarorganize_dictionary();
extern void G__cpp_setup_globalorganize_dictionary();
extern void G__cpp_setup_memfuncorganize_dictionary();
extern void G__cpp_setup_funcorganize_dictionary();
extern void G__set_cpp_environmentorganize_dictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../Include/organizetree.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__organize_dictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__organize_dictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__organize_dictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__organize_dictionaryLN_SiHit;
extern G__linked_taginfo G__organize_dictionaryLN_SiHitcLcLSortByDetector;
extern G__linked_taginfo G__organize_dictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__organize_dictionaryLN_SiHitcLcLSortByHit;
extern G__linked_taginfo G__organize_dictionaryLN_vectorlESiHitcLcLSortByDetectorcOallocatorlESiHitcLcLSortByDetectorgRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_reverse_iteratorlEvectorlESiHitcLcLSortByDetectorcOallocatorlESiHitcLcLSortByDetectorgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__organize_dictionaryLN_vectorlESiHitcLcLSortByHitcOallocatorlESiHitcLcLSortByHitgRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_reverse_iteratorlEvectorlESiHitcLcLSortByHitcOallocatorlESiHitcLcLSortByHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__organize_dictionaryLN_PCHit;
extern G__linked_taginfo G__organize_dictionaryLN_PCHitcLcLSortByPC;
extern G__linked_taginfo G__organize_dictionaryLN_vectorlEPCHitcLcLSortByPCcOallocatorlEPCHitcLcLSortByPCgRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_reverse_iteratorlEvectorlEPCHitcLcLSortByPCcOallocatorlEPCHitcLcLSortByPCgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__organize_dictionaryLN_SETTINGS;
extern G__linked_taginfo G__organize_dictionaryLN_SETTINGScLcLset_values;
extern G__linked_taginfo G__organize_dictionaryLN_Track;
extern G__linked_taginfo G__organize_dictionaryLN_TrackcLcLTrackEvent;
extern G__linked_taginfo G__organize_dictionaryLN_TrackcLcLSilicon_Event;
extern G__linked_taginfo G__organize_dictionaryLN_TrackcLcLPropCounter_Event;
extern G__linked_taginfo G__organize_dictionaryLN_TrackcLcLBe8Event;
extern G__linked_taginfo G__organize_dictionaryLN_TrackcLcLAl27Event;
extern G__linked_taginfo G__organize_dictionaryLN_vectorlETrackcLcLTrackEventcOallocatorlETrackcLcLTrackEventgRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_reverse_iteratorlEvectorlETrackcLcLTrackEventcOallocatorlETrackcLcLTrackEventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__organize_dictionaryLN_vectorlETrackcLcLSilicon_EventcOallocatorlETrackcLcLSilicon_EventgRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_reverse_iteratorlEvectorlETrackcLcLSilicon_EventcOallocatorlETrackcLcLSilicon_EventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__organize_dictionaryLN_vectorlETrackcLcLPropCounter_EventcOallocatorlETrackcLcLPropCounter_EventgRsPgR;
extern G__linked_taginfo G__organize_dictionaryLN_reverse_iteratorlEvectorlETrackcLcLPropCounter_EventcOallocatorlETrackcLcLPropCounter_EventgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
